# -*- coding: utf-8 -*-
{
    'name': 'MedVet',
    'version': '1',
    'summary': 'Gestión veterinaria',
    'sequence': -100,
    'description': """MedVet - Gestión veterinaria""",
    'author': 'Maximiliano Medina',
    'maintainer': 'Maximiliano Medina',
    'website': 'https://www.medvet.com',
    'license': 'AGPL-3',
    'depends': [
        # 'sale',
        'mail',
        # 'website_slides',
        # 'hr',
    ],
    'data': [
        'data/paciente.especie.csv',
        'data/paciente.raza.csv',
        'data/item.grupo.csv',
        'data/item.rubro.csv',
        'data/item.categoria.csv',
        'data/item.fabricante.csv',
        'data/secuencia.xml',
        'data/aviso.xml',
        'security/ir.model.access.csv',
        'views/paciente.xml',
        'views/practica.xml',
        'views/item.xml',
        'views/turno.xml',
        'views/personal.xml',
        'views/especie.xml',
        'views/raza.xml',
        'views/grupo.xml',
        'views/rubro.xml',
        'views/categoria.xml',
        'views/fabricante.xml',
        'views/cliente.xml',
        'reports/report.xml',
        'reports/historia_clinica_template.xml',
        'reports/turno_agenda_semanal_template.xml',
        'data/turno_automation.xml'
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'qweb': [],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
